language: python
python: 3.8.1

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - bash <(curl -s https://codecov.io/bash)

script:
  - coverage run manage.py test && flake8
