language: python
python: 3.8.1

install:
  - cd backend
  - pip install pipenv
  - pipenv install --dev

script:
  - coverage run manage.py test && flake8

after_script:
  - bash <(curl -s https://codecov.io/bash)
