version: "3.5"

services:
  web:
    container_name: wildrace-web
    build: .
    image: phpusr/wildrace
    restart: unless-stopped
    ports:
      - ${PORT:-8010}:8000
    environment:
      - DEBUG=False
      - APP_LOG_LEVEL=DEBUG
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/app
      - REDIS_URL=redis://redis:6379
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - SENTRY_BACKEND_DSN=${SENTRY_BACKEND_DSN}
    volumes:
      - ./data/db:/app/data
    depends_on:
      - db
      - redis

  db:
    container_name: wildrace-db
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  redis:
    container_name: wildrace-redis
    image: redis:5.0
    restart: unless-stopped

networks:
  default:
    name: wildrace_default
