version: "3.5"

services:
  web:
    container_name: wildrace-web
    build: .
    image: phpusr/wildrace
    restart: unless-stopped
    ports:
      - 8010:8000
    environment:
      - DEBUG=False
      - APP_LOG_LEVEL=DEBUG
      - PORT=8000
      - DATABASE_URL=postgres://postgres:mysuperpassword@db:5432/app
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    container_name: wildrace-db
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysuperpassword

  redis:
    container_name: wildrace-redis
    image: redis:5.0
    restart: unless-stopped

networks:
  default:
    name: wildrace_default
