# Generated by Django 3.0.2 on 2020-01-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_statlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='statlog',
            name='stat_type',
            field=models.IntegerField(choices=[(0, 'Distance'), (1, 'Date')], default=0),
            preserve_default=False,
        ),
    ]
