# Generated by Django 3.0.2 on 2020-01-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_max',
            field=models.URLField(blank=True),
        ),
    ]
