# Generated by Django 3.0.2 on 2020-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200130_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
