# Generated by Django 3.0.3 on 2020-02-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200131_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='group_short_link',
        ),
    ]
