# Generated by Django 3.0.2 on 2020-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200130_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('start_value', models.CharField(max_length=100)),
                ('end_value', models.CharField(max_length=100)),
                ('post_id', models.IntegerField()),
            ],
        ),
    ]
