# Generated by Django 3.0.3 on 2020-03-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_config_group_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='sync_seconds',
        ),
    ]
