# Generated by Django 3.0.4 on 2020-03-09 09:44
from django.contrib.auth import get_user_model
from django.db import migrations
from django.utils import timezone


def create_required_data(apps, schema_editor):
    User = get_user_model()
    username = 'phpusr'
    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(username, password='mysuperpassword')

    Config = apps.get_model('app', 'Config')
    if not Config.objects.exists():
        Config.objects.create(
            sync_posts=False,
            group_id='88923650',
            commenting=False,
            comment_access_token='',
            comment_from_group=False,
            publish_stat=False
        )

    TempData = apps.get_model('app', 'TempData')
    if not TempData.objects.exists():
        TempData.objects.create(last_sync_date=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_config_sync_seconds'),
    ]

    operations = [
        migrations.RunPython(create_required_data)
    ]
