# Generated by Django 3.0.7 on 2022-10-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200309_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='comment_access_token',
            field=models.TextField(max_length=255),
        ),
    ]
