# Generated by Django 3.0.14 on 2025-09-09 17:13

from django.db import migrations, models, connection


def set_vk_id(apps, schema_editor):
    Post = apps.get_model('app', 'Post')
    current_id = 1

    with connection.cursor() as cursor:
        for post in Post.objects.order_by('date'):
            cursor.execute("UPDATE app_post SET id = %s, vk_id = %s WHERE id = %s", [current_id, post.id, post.id])
            current_id += 1

        cursor.execute("ALTER SEQUENCE app_post_id_seq RESTART WITH %s;", [current_id])

def unset_vk_id(apps, schema_editor):
    Post = apps.get_model('app', 'Post')

    with connection.cursor() as cursor:
        for post in Post.objects.all():
            cursor.execute("UPDATE app_post SET id = %s, vk_id = 0 WHERE id = %s", [post.vk_id, post.id])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20241021_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vk_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(set_vk_id, unset_vk_id),
    ]
